---
title: "Overview"
author: "[Statistical Genetics Lab](http://statgen.esalq.usp.br) <br/> Department of Genetics <br/> Luiz de Queiroz College of Agriculture <br/> University of São Paulo"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Overview}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r knitr_init, echo=FALSE, cache=FALSE}
library(knitr)
library(rmarkdown)

knitr::opts_chunk$set(collapse = TRUE,
                      comment = "#>",
                      fig.width = 6,
                      fig.height = 6,
                      fig.align = "center",
                      dev = "png",
                      dpi = 36,
                      cache = TRUE)

```

_OneMap_ is an environment for constructing linkage maps in several
experimental crosses, including outcrossing (full-sib families derived
from two non-homozygous parents), RILs, F$_2$ and backcrosses.

It is implemented as a package to be used under the freely distributed
R software, which is a language and environment for statistical
computing ([www.r-project.org](https://www.r-project.org/)). It is designed to
be fully integrated with R/qtl package (Broman and Sen, 2009) and
Windows QTL Cartographer (Wang et al., 2010) in order to do QTL
mapping for RILs, F$_2$ and backcrosses. New functions for doing QTL
mapping in outcrossing species (e. g. using models from Gazaffi et al.
2014) are under development and will be included in a near future.

Wu et al. (2002a) proposed a methodology to construct genetic maps in
outcrossing species, which allows the analysis of a mixed set of
different marker types containing various segregation patterns. It
also allows the simultaneous estimation of linkage and linkage phases
between markers. Combined with ideas from Wu et al. (2002b) for doing
multipoint analysis based on hidden Markov models (HMMs), it provides
an excellent framework for genetic mapping in outcrossing species, in
a similar way as for inbred-based populations, commonly analyzed by
packages such as MAPMAKER/EXP (Lander et al., 1987).

This method was implemented in _OneMap_ and was tested through
extensive simulations. It was also successfully applied by author(s)
of the packages and their collaborators in the construction of genetic
maps of sugarcane (Garcia et al., 2006; Oliveira et al., 2007;
Palhares et al. 2013), _Passiflora_ (Oliveira et al., 2008; Pereira et
al., 2013), rubber tree (Souza et al., 2013) and _Acca sellowiana_
(Quezada et al., 2014). Actually, the analysis of these data sets
motivated the implementation of the first release of _OneMap_
(Margarido et al., 2007) and all its subsequent updates.

In version 2.0-0, we included several major modifications to take
advantage of the fact that some segregation patterns that occur in
outcrossing populations can also occur in populations derived from
inbred lines (i.e. RILs, F$_2$ and backcrosses). For example, a marker
that segregates in a 1:2:1 fashion in the outcrossing context can be
viewed as a co-dominant marker in F$_2$ populations. The main
difference is that, for the latter, there is no need to estimate
linkage phases.

Using these ideas, we adapted _OneMap_ to also construct genetic maps
for RILs, F$_2$ and backcross populations, all incorporating the
advantages of the HMMs. Moreover, we also implemented three new
ordering algorithms. Version 1.0-0 had Rapid Chain Delineation - RCD
(Doerge, 1996) and TRY (Lander et al., 1987); starting in version
2.0-0, the new ones available are Seriation - SER (Buetow and
Chakravarti, 1987), recombination counting and ordering - RECORD (Van
Os et al., 2005) and unidirectional growth - UG (Tan and Fu, 2006).
They can be used for all experimental crosses included in _OneMap_,
and can be chosen to give the best result for any situation faced by
the user (Mollinari et al., 2009).

_OneMap_ is available as source code for Windows, Linux and Mac OS. It
is released under the GNU General Public License, is open-source and
the code can be changed freely. It comes with no warranty.

No advanced knowledge in R is required to use _OneMap_. Several
researchers around the world had contacted us to provide feedback and
suggestions. If you do not know R, we wrote a short vignette with and
introduction to R, where we address the basic knowledge required to
start using _OneMap_. People with some knowledge of R may just skip
this part.

We also wrote a chapter with information about _OneMap_ installation,
as well as sections showing the usage of _OneMap_ to build linkage
maps for outcrossing (non-inbred) populations, as well as F$_2$
populations (which can also be applied to backcrosses and RILs).

All sections may be read independently. So, you can just move to the
part you are interested. Good luck, and let us know if you have
suggestions to improve the package!

# How to Cite

Margarido G. R. A., Souza A. P., Garcia A. A. F., 2007. OneMap:
software for genetic mapping in outcrossing species. _Hereditas_
**144**: 78–79.

# References

Broman K. W., Sen Ś., 2009. A Guide to QTL Mapping with R/qtl.
Springer, New York.

Wang S., Basten, C. J. and Zeng Z.-B. Windows QTL Cartographer 2.5.
Department of Statistics, North Carolina State University, Raleigh,
NC, 2010.
[http://statgen.ncsu.edu/qtlcart/WQTLCart.htm](http://statgen.ncsu.edu/qtlcart/WQTLCart.htm)

Wu, R., Ma, C.X., Painter, I. and Zeng, Z.-B. 2002a. Simultaneous
maximum likelihood estimation of linkage and linkage phases in
outcrossing species. _Theoretical Population Biology_ **61**: 349-363.

Wu, R., Ma, C.-X., Wu, S. S. and Zeng, Z.-B. 2002b. Linkage mapping of
sex-specific differences. _Genetical Research_ **79**: 85-96.

Gazaffi R., Margarido G. R. A., Pastina M. M., Mollinari M., Garcia A.
A. F., 2014. A model for quantitative trait loci mapping, linkage
phase, and segregation pattern estimation for a full-sib progeny.
_Tree Genet. Genomes_ **10**: 791–801.

Lander, E.S., Green, P., Abrahanson, J., Barlow, A., Daly, M.J.,
Lincoln, S.E. and Newburg, L. 1987. MAPMAKER, An interactive computing
package for constructing primary genetic linkage maps of experimental
and natural populations. _Genomics_ **1**: 174-181.

Garcia A. A. F., Kido E. A., Meza A. N., Souza H. M. B., Pinto L. R.,
Pastina M. M., Leite C. S., Silva J. A. G. da, Ulian E. C., Figueira
A. V, Souza A. P., 2006. Development of an integrated genetic map of a
sugarcane (_Saccharum spp._) commercial cross, based on a
maximum-likelihood approach for estimation of linkage and linkage
phases. _Theor. Appl. Genet._ **112**: 298–314.

Oliveira K. M., Pinto L. R., Marconi T. G., Margarido G. R. A.,
Pastina M. M., Teixeira L. H. M., Figueira A. V, Ulian E. C., Garcia
A. A. F., Souza A. P., 2007. Functional integrated genetic linkage map
based on EST-markers for a sugarcane (Saccharum spp.) commercial
cross. _Mol. Breed._ **20**: 189–208.

Palhares A. C., Rodrigues-Morais T. B., Sluys M.-A. Van, Domingues D.
S., Maccheroni W., Jordão H., Souza A. P., Marconi T. G., Mollinari
M., Gazaffi R., Garcia A. A. F., Vieira M. L. C., 2012. A novel
linkage map of sugarcane with evidence for clustering of
retrotransposon-based markers. _BMC Genet._ **13**: 51.

Oliveira E. J., Vieira M. L. C., Garcia A. A. F., Munhoz C. F.,
Margarido G. R. A., Consoli L., Matta F. P., Moraes M. C., Zucchi M.
I., Fungaro M. H. P., 2008. An Integrated Molecular Map of Yellow
Passion Fruit Based on Simultaneous Maximum-Likehood Estimation of
Linkage and Linkage Phases. _J. Am. Soc. Hortic. Sci._ **133**: 35–41.

Pereira G. S., Nunes E. S., Laperuta L. D. C., Braga M. F., Penha H.
a., Diniz A. L., Munhoz C. F., Gazaffi R., Garcia A. a. F., Vieira M.
L. C., 2013. Molecular polymorphism and linkage analysis in sweet
passion fruit, an outcrossing species. _Ann. Appl. Biol._ **162**:
347–361.

Souza L. M., Gazaffi R., Mantello C. C., Silva C. C., Garcia D., Guen
V. Le, Cardoso S. E. A., Garcia A. A. F., Souza A. P., 2013. QTL
Mapping of Growth-Related Traits in a Full-Sib Family of Rubber Tree
(Hevea brasiliensis) Evaluated in a Sub-Tropical Climate. _PLoS One_
**8**: e61238.

Quezada M., Pastina M. M., Ravest G., Silva P., Vignale B., Cabrera
D., Hinrichsen P., Garcia A. A. F., Pritsch C., 2014. A first genetic
map of Acca sellowiana based on ISSR, AFLP and SSR markers. _Sci.
Hortic._ **169**: 138–146.

Doerge, R.W. 1996. Constructing genetic maps by rapid chain
delineation. _Journal of Agricultural Genomics_ **2**.

Buetow, K. H., Chakravarti, A. 1987. Multipoint gene mapping using
seriation. I. General methods. _American Journal of Human Genetics_
**41**: 180-188.

Van Os H, Stam P, Visser R.G.F., Van Eck H.J. 2005. RECORD: a novel
method for ordering loci on a genetic linkage map. _Theor. Appl.
Genet._ **112**: 30-40.

Tan, Y., Fu, Y. 2006. A novel method for estimating linkage maps.
_Genetics_ **173**: 2383-2390.

Mollinari, M., Margarido, G. R. A., Vencovsky, R. and Garcia, A. A.
F. 2009. Evaluation of algorithms used to order markers on genetics
maps. _Heredity_ **103**: 494-502.
