# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Run HMM chains
#' 
#' @param geno_R genotypes
#' @param error_R genotypes probabilities
#' @param type_R marker types
#' @param phase_R phase estimated by 2-pts
#' @param rf_R recombination fraction
#' @param verbose_R logical to display or not the procedure
#' @param tol_R EM algorithm tolerance
#' 
#' @return a list containing the re-estimated vector of recombination
#'      fractions and the logarithm of the likelihood
#' 
#' @export
#' 
est_hmm_out <- function(geno_R, error_R, type_R, phase_R, rf_R, verbose_R, tol_R) {
    .Call('_onemap_est_hmm_out', PACKAGE = 'onemap', geno_R, error_R, type_R, phase_R, rf_R, verbose_R, tol_R)
}

