# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Run HMM chains
#' 
#' @export
#' 
est_hmm_out <- function(geno_R, error_R, type_R, phase_R, rf_R, verbose_R, tol_R) {
    .Call('_onemap_est_hmm_out', PACKAGE = 'onemap', geno_R, error_R, type_R, phase_R, rf_R, verbose_R, tol_R)
}

